# Generated by Django 6.0.6 on 2026-09-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_user_id',
            field=models.CharField(blank=True, help_text='Biometric device User ID / PIN for ZKTeco attendance', max_length=20, null=True, unique=True),
        ),
    ]
