# Generated by Django 6.0.6 on 2026-06-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('system_admin', 'System Administrator'), ('ceo', 'CEO')], default='employee', max_length=20),
        ),
    ]
