# Generated by Django 6.0.6 on 2026-06-14 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decision_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='duration',
            field=models.CharField(choices=[('full', 'Full Day(s)'), ('am', 'Half Day – Morning'), ('pm', 'Half Day – Afternoon')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='handover_to',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='color',
            field=models.CharField(default='#4299e1', help_text='Hex color for balance bar', max_length=7),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type')},
        ),
    ]
