# Generated by Django 6.0.6 on 2026-06-16 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_publicholiday_alter_leaverequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='duration',
        ),
    ]
