# Generated by Django 6.0.6 on 2026-07-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_staffmovement_purpose_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmovement',
            name='purpose_type',
            field=models.CharField(blank=True, choices=[('problem_solving', 'Problem solving'), ('amc', 'AMC'), ('goods_bill_delivery', 'Goods / bill delivery'), ('goods_pickup', 'Goods pickup'), ('document_delivery', 'Document delivery')], max_length=30),
        ),
    ]
