# Generated by Django 6.0.6 on 2026-07-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_alter_staffmovement_purpose_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmovement',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffmovement',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
