# Generated by Django 6.0.6 on 2026-07-19 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_staffmovement_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayworkrequest',
            name='comp_off_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayworkrequest',
            name='comp_off_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holidayworkrequest',
            name='comp_off_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_off_marked_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='purpose_type',
            field=models.CharField(blank=True, choices=[('problem_solving', 'Problem solving'), ('amc', 'AMC Support'), ('repair', 'Repair / Service'), ('goods_bill_delivery', 'Goods / bill delivery'), ('goods_pickup', 'Goods pickup'), ('document_delivery', 'Document delivery'), ('bank', 'Bank visit')], max_length=30),
        ),
    ]
