# Generated by Django 6.0.6 on 2026-06-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_alter_leavebalance_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='total_days',
        ),
    ]
