# Generated by Django 6.0.6 on 2026-08-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_holidayworkrequest_comp_off_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmovement',
            name='work_done_for',
            field=models.CharField(blank=True, help_text='Contact person or department at client site', max_length=200),
        ),
    ]
