# Generated by Django 6.0.6 on 2026-08-31 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_staffmovement_work_done_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMovementStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('client', models.CharField(max_length=200)),
                ('work_done_for', models.CharField(blank=True, help_text='Contact person or department at client site', max_length=200)),
                ('purpose_type', models.CharField(blank=True, choices=[('problem_solving', 'Problem solving'), ('amc', 'AMC Support'), ('repair', 'Repair / Service'), ('goods_bill_delivery', 'Goods / bill delivery'), ('goods_pickup', 'Goods pickup'), ('document_delivery', 'Document delivery'), ('bank', 'Bank visit')], max_length=30)),
                ('completion_notes', models.TextField(blank=True, help_text='Completion notes for this specific client')),
                ('problem_description', models.TextField(blank=True)),
                ('resolution_status', models.CharField(blank=True, choices=[('solved', 'Solved'), ('not_solved', 'Not solved')], max_length=20)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='leaves.staffmovement')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
