# Generated by Django 6.0.6 on 2026-06-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_attendancerequest_holidayworkrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='handover_to',
        ),
    ]
