# Generated by Django 4.2.26 on 2026-07-10 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0007_remove_leaverequest_handover_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client', models.CharField(max_length=200)),
                ('out_time', models.TimeField()),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-out_time'],
            },
        ),
    ]
