# Generated by Django 6.0.6 on 2026-09-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_staffmovementstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmovementstop',
            name='purpose',
            field=models.TextField(blank=True, help_text='Additional notes / specific purpose for this stop'),
        ),
    ]
