# Generated by Django 6.0.6 on 2026-07-12 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_staffmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmovement',
            name='assistants',
            field=models.ManyToManyField(blank=True, help_text='Other staff who accompanied this movement', related_name='assisted_movements', to=settings.AUTH_USER_MODEL),
        ),
    ]
