# Generated by Django 6.0.6 on 2026-09-14 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_staffmovementstop_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, help_text="Friendly name, e.g. 'Office Main Entrance'", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(help_text='PIN / User ID from the biometric device', max_length=20)),
                ('timestamp', models.DateTimeField(help_text='Punch date/time from the device')),
                ('status', models.IntegerField(choices=[(0, 'Check-in'), (1, 'Check-out'), (2, 'Break-out'), (3, 'Break-in'), (4, 'Overtime-in'), (5, 'Overtime-out')], default=0)),
                ('verify_mode', models.IntegerField(blank=True, choices=[(0, 'Password'), (1, 'Fingerprint'), (2, 'Card'), (15, 'Face')], null=True)),
                ('work_code', models.CharField(blank=True, max_length=20)),
                ('raw_data', models.TextField(blank=True, help_text='Original line from device for debugging')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, help_text='Resolved Django user (auto-matched via device_user_id)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='leaves.biometricdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('device_user_id', 'timestamp', 'device')},
            },
        ),
    ]
