# Generated by Django 6.0.6 on 2026-09-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0009_biometricdevice_attendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicholiday',
            name='applicable_to',
            field=models.CharField(choices=[('all', 'All Staff'), ('female', 'Female Staff Only')], default='all', help_text='Whether this holiday applies to all staff or female staff only (e.g. Teej)', max_length=20),
        ),
    ]
