# Generated by Django 5.2 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0009_staffmovement_assistants"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmovement",
            name="problem_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="staffmovement",
            name="purpose_type",
            field=models.CharField(blank=True, choices=[("problem_solving", "Problem solving"), ("goods_bill_delivery", "Goods / bill delivery"), ("goods_pickup", "Goods pickup")], max_length=30),
        ),
        migrations.AddField(
            model_name="staffmovement",
            name="resolution_status",
            field=models.CharField(blank=True, choices=[("solved", "Solved"), ("not_solved", "Not solved")], max_length=20),
        ),
    ]
