# Generated by Django 6.0.6 on 2026-09-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0010_publicholiday_applicable_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmovementstop',
            name='in_time',
            field=models.TimeField(blank=True, help_text='Return / Finish time for this client stop', null=True),
        ),
        migrations.AddField(
            model_name='staffmovementstop',
            name='out_time',
            field=models.TimeField(blank=True, help_text='Departure / Start time for this client stop', null=True),
        ),
        migrations.AddField(
            model_name='staffmovementstop',
            name='services',
            field=models.JSONField(blank=True, default=list, help_text='List of service / repair checkboxes'),
        ),
        migrations.CreateModel(
            name='StaffMovementDepartmentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('department', models.CharField(help_text='Department / Section / Division / Position', max_length=150)),
                ('work_done_for', models.CharField(blank=True, help_text='Contact person / username at department', max_length=200)),
                ('work_description', models.TextField(blank=True, help_text='What work done ??')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_works', to='leaves.staffmovementstop')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
