# Generated by Django 5.2 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0010_staffmovement_purpose_and_resolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmovement",
            name="completion_notes",
            field=models.TextField(blank=True),
        ),
    ]
