# Generated by Django 6.0.6 on 2026-07-15 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0011_staffmovement_completion_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmovement',
            name='logged_by',
            field=models.ForeignKey(blank=True, help_text='Set when this record was submitted by someone other than the employee (e.g. logged on their behalf).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_logged_on_behalf', to=settings.AUTH_USER_MODEL),
        ),
    ]
