# Generated by Django 6.0.6 on 2026-09-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0011_staffmovementstop_in_time_staffmovementstop_out_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmovement',
            name='problem_description',
        ),
        migrations.RemoveField(
            model_name='staffmovement',
            name='resolution_status',
        ),
        migrations.RemoveField(
            model_name='staffmovementassistant',
            name='resolution_status',
        ),
        migrations.RemoveField(
            model_name='staffmovementstop',
            name='problem_description',
        ),
        migrations.RemoveField(
            model_name='staffmovementstop',
            name='resolution_status',
        ),
        migrations.AlterField(
            model_name='staffmovement',
            name='purpose_type',
            field=models.CharField(blank=True, choices=[('amc', 'AMC Support'), ('repair', 'Repair / Service'), ('goods_bill_delivery', 'Goods / bill delivery'), ('goods_pickup', 'Goods pickup'), ('document_delivery', 'Document delivery'), ('bank', 'Bank visit')], max_length=30),
        ),
        migrations.AlterField(
            model_name='staffmovementstop',
            name='purpose_type',
            field=models.CharField(blank=True, choices=[('amc', 'AMC Support'), ('repair', 'Repair / Service'), ('goods_bill_delivery', 'Goods / bill delivery'), ('goods_pickup', 'Goods pickup'), ('document_delivery', 'Document delivery'), ('bank', 'Bank visit')], max_length=30),
        ),
    ]
